// Data mirrors the Enfinito Restaurant Growth Packages sheet. BDT only.
export const PACKAGES = [
  {
    id: 'starter',
    icon: 'Sprout',
    name: 'Starter',
    bestFor: 'Small restaurants & cafés',
    seating: 'Up to 40 seats',
    price: 'BDT 20,000',
    period: '/mo',
    highlights: [
      '4 reels + 8 static posts a month',
      'Production day every 3 months',
      'Food photography, up to 10 items',
      'Facebook, Instagram & Google profile',
      'Meta ads management',
      'Monthly report & strategy meeting',
    ],
  },
  {
    id: 'popular',
    icon: 'TrendingUp',
    name: 'Popular',
    featured: true,
    bestFor: 'Growing restaurants',
    seating: 'Up to 40 seats',
    price: 'BDT 35,000',
    period: '/mo',
    highlights: [
      '8 reels + 16 static posts a month',
      'Production day every 2 months',
      'Food photography, up to 20 items',
      'Adds TikTok, festival & offer campaigns',
      'Remarketing + pixel tracking',
      'Dedicated account manager',
    ],
  },
  {
    id: 'signature',
    icon: 'Crown',
    name: 'Signature',
    bestFor: 'Premium restaurants & multi-branches',
    seating: '40+ seats',
    price: 'BDT 55,000',
    period: '/mo',
    highlights: [
      '12 reels + 24 static posts a month',
      'A production day every month',
      'Full menu photography coverage',
      'Weekly dashboard & strategy meetings',
      'Up to 5 PR / influencer campaigns',
      'Priority manager + WhatsApp support',
    ],
  },
]
