// Data mirrors the Enfinito Restaurant Growth Packages sheet. BDT only.
export const PACKAGES = [
  {
    id: 'starter',
    icon: 'Sprout',
    name: 'Starter',
    bestFor: 'small restaurants & cafés',
    seating: 'up to 40 seats',
    price: 'BDT 20,000',
    period: '/mo',
    highlights: [
      '4 reels + 8 static posts a month',
      'production day every 3 months',
      'food photography, up to 10 items',
      'facebook, instagram & google profile',
      'meta ads management',
      'monthly report & strategy meeting',
    ],
  },
  {
    id: 'popular',
    icon: 'TrendingUp',
    name: 'Popular',
    featured: true,
    bestFor: 'growing restaurants',
    seating: '41–80 seats',
    price: 'BDT 35,000',
    period: '/mo',
    highlights: [
      '8 reels + 16 static posts a month',
      'production day every 2 months',
      'food photography, up to 20 items',
      'adds tiktok, festival & offer campaigns',
      'remarketing + pixel tracking',
      'dedicated account manager',
    ],
  },
  {
    id: 'signature',
    icon: 'Crown',
    name: 'Signature',
    bestFor: 'premium restaurants & multi-branches',
    seating: '80+ seats',
    price: 'BDT 55,000',
    period: '/mo',
    highlights: [
      '12 reels + 24 static posts a month',
      'a production day every month',
      'full menu photography coverage',
      'weekly dashboard & strategy meetings',
      'up to 5 pr / influencer campaigns',
      'priority manager + whatsapp support',
    ],
  },
]
